import { Inter,Poppins } from "next/font/google";
import "./globals.css";
import TanstackQuery from "@/providers/TanstackQuery";
import NxtProvider from "@/providers/NextProvider";
import { Toaster } from "react-hot-toast";
import StoreProvider from "@/providers/StoreProvider";

const inter = Inter({ subsets: ["latin"] });

const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Chat App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
      
      <Toaster />
        <TanstackQuery>
        <StoreProvider>
          <NxtProvider>{children}</NxtProvider>
          </StoreProvider>
        </TanstackQuery>
       
      </body>
    </html>
  );
}
