import { Inter } from "next/font/google";
import "./globals.css";
import TanstackQuery from "@/providers/TanstackQuery";
import dynamic from "next/dynamic";
import NxtProvider from "@/providers/NextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Chat App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TanstackQuery>
          <NxtProvider>{children}</NxtProvider>
        </TanstackQuery>
      </body>
    </html>
  );
}
